### ISSUE TITLE
preprocess.py无法正常运行

### ISSUE THREAD

**Issue by KOKOWORK** [pubuyun/VocaloidAITuner#1]
该文件运行时只能提示每个文件Error，只有一个文件时raise如下：
```
50.0 `%`
Error in 1
Traceback (most recent call last):
  File "无效打码\preprocess.py", line 38, in <module>
    length = max(int(track.return_all_cc()[-1].t), int(track.return_all_note()[-1].t) + int(track.return_all_note()[-1].dur))
IndexError: list index out of range
```

**Comment by pubuyun** [comment]
这是因为vsqxt只支持vocaloid4的格式，如果vsqxt获取不到音符就会报错

**Comment by KOKOWORK** [comment]
感谢回复
使用test.vsqx测试，出现了新问题：
python preprocess.py
```
100.0 %
146160
Error in 1
Traceback (most recent call last):
  File "...\VocaloidAITuner-main\preprocess.py", line 113, in <module>
    df.to_csv('testfiles/data.csv', index=False)
  File "...\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "...\锦依卫\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
  File "...\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "...\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "...\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'testfiles'
```

**Comment by KOKOWORK** [comment]
哦，这两个文件夹要手动建
暂时没有问题了
